adminpanel/urls.py
from django.urls import path
from . import views

app_name = 'admin_panel'

urlpatterns = [
    path('', views.admin_panel, name='management'),
    path('ticket_details_admin/<int:id>/', views.ticket_details_admin_panel, name='ticket_details_admin'),
    path('add_ticketcomment_admin/<int:id>/', views.add_ticketcomment_admin, name='add_ticketcomment_admin'),
    path('orders_list_admin/', views.orders_list_admin, name='orders_list_admin'),
    path('tickets_list_admin/', views.tickets_list_admin, name='tickets_list_admin'),
    path('products_list_admin/', views.products_list_admin, name='products_list_admin'),
    path('contact_list_admin/', views.contact_list_admin, name='contact_list_admin'),
    path('contact_details_admin/<int:id>/', views.contact_details_admin, name='contact_details_admin'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('blog_details/<str:slug>', views.blog_details, name='blog_details'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('contact/', views.contact, name = 'contact'),
    path('product_list', views.product_list, name = 'product_list'),
    path('product_list/<str:category_slug>/', views.product_list, name = 'product_list_category'),
    path('product_list_brand/<str:brand_slug>/', views.product_list, name = 'product_list_brand'),
    path('product_detail/<int:id>/<str:slug>/', views.product_detail, name='product_detail'),
    path('addـcomment/<int:id>/', views.add_comment, name='add_comment'),
]

adminpanel/models.py
from django.db import models

# Create your models here.

orders/models.py
from decimal import Decimal
from django.db import models
from accounts.models import User
from products.models import Product
from coupons.models import Coupon
from django.core.validators import MinValueValidator, MaxValueValidator
from extensions.utils import jalali_converter


# Create your models here.
class Order(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    first_name = models.CharField('نام', max_length=64)
    last_name = models.CharField('نام خانوادگی', max_length=64)
    city = models.CharField('شهر', max_length=128)
    address = models.CharField('آدرس', max_length=256)
    postal_code = models.CharField('کد پستی', max_length=16)
    phone_number = models.CharField('شماره تلفن', max_length=11)
    paid = models.BooleanField('پرداخت شد', default=False)
    order_code = models.CharField('کد سفارش', max_length=8)
    
    PENDING = 1
    SENDED = 2
    CANCELED = 3
    STATUS_CHOICES = (
        (PENDING, 'در حال بررسی'),
        (SENDED, 'ارسال شد'),
        (CANCELED, 'کنسل شد'),
    )
    status = models.IntegerField('وضعیت', choices=STATUS_CHOICES, default=1)

    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, related_name='orders', null=True, blank=True, verbose_name='کد تخفیف')
    discount = models.IntegerField('تخفیف', default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])

    created_at = models.DateTimeField('تاریخ ایجاد', auto_now_add=True)
    updated_at = models.DateTimeField('تاریخ بروز رسانی', auto_now=True)

    

    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارشات'
        ordering = ('-created_at', )

    def __str__(self):
        return self.user.username

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * (self.discount / Decimal(100)) 

    get_total_cost.short_description = 'مبلغ کل'

    def jcreated_at(self):
        return jalali_converter(self.created_at)
    jcreated_at.short_description = 'تاریخ سفارش'  

    def jupdated_at(self):
        return jalali_converter(self.updated_at)
    jupdated_at.short_description = 'تاریخ به روز کردن سفارش' 




class OrderItem(models.Model):
    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارشات'

    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items', verbose_name='سفارش')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items', verbose_name='محصول')
    price = models.PositiveIntegerField('قیمت')
    quantity = models.PositiveIntegerField('تعداد', default=1)
    total_price = models.PositiveIntegerField('قیمت کامل')

    def __str__(self):
        return self.product.name

    def get_cost(self):
        return self.quantity * self.price  

adminpanel/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from accounts.models import User
from products.models import Product, Contact
from orders.models import Order, OrderItem
from tickets.models import Ticket, TicketComment
from tickets.forms import TicketCommentCreateForm, TicketCommentCreateAdminForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.utils import timezone

from django.core.mail import send_mail


# Create your views here.

def admin_panel(request):
    sale = OrderItem.objects.values('order__status', 'product__name').annotate(Sum('quantity'), Sum('total_price')).order_by('-quantity__sum').filter(order__status=2)
    
    return render(request, 'adminlte/admin_panel.html', {
        'sale': sale,
        'open_tickets': Ticket.objects.exclude(status=4),
        'users_count': User.objects.all().count(),
        'product_count': Product.objects.all().count(),
        'orders_count': Order.objects.all().count(),
        'orders': Order.objects.filter(status=1),
        'ticket_count': Ticket.objects.all().count(),
        'contact': Contact.objects.all()[:6],
    })

def ticket_details_admin_panel(request, id):
    ticket = get_object_or_404(Ticket, id=id)
    ticketcomment = TicketComment.objects.filter(ticket_id=id)

    return render(request, 'adminlte/ticket_details_admin_panel.html', {
        'ticket': ticket,
        'ticketcomment': ticketcomment,
    })
        
def add_ticketcomment_admin(request, id):
    url = request.META.get('HTTP_REFERER')  
    if request.method == 'POST':
        form = TicketCommentCreateForm(request.POST)
        if form.is_valid():
            comment = TicketComment()
            comment.text = form.cleaned_data['text']
            comment.image = form.cleaned_data['image']
            comment.ticket_id = id
            comment.author_id = request.user.id 
            comment.ticket.updated_at = timezone.now()
            comment.save()
            comment.ticket.save()
            messages.success(request, 'جواب با موفقیت ثبت گردید')
            # تنظیمات ارسال فاکتور خرید با ایمیل
            subject = 'جواب شما فرستاده شد'
            message = f'با سلام و خسته نباشید {request.user.username}'
            
            send_mail(subject,
            message,
            'coolgertn@gmail.com', 
            [comment.ticket.user.email], 
            fail_silently=False)

            return HttpResponseRedirect(url)
    else:
        form = TicketCommentCreateForm()
    return HttpResponseRedirect(url)
    
def orders_list_admin(request):
    orders = Order.objects.all()
    return render(request, 'adminlte/order_list_admin.html', {
        'orders': orders,
    })   

def tickets_list_admin(request):
    tickets = Ticket.objects.all()
    return render(request, 'adminlte/tickets_list_admin.html', {
        'tickets': tickets,
    })     

def products_list_admin(request):
    products = Product.objects.all()
    return render(request, 'adminlte/products_list_admin.html', {
        'products': products,
    })

def contact_list_admin(request):
    contact = Contact.objects.all()

    return render(request, 'adminlte/contact_list_admin.html', {
        'contact': contact,
    }) 

def contact_details_admin(request, id):
    contact = get_object_or_404(Contact, id=id)
    return render(request, 'adminlte/contact_details_admin.html', {
        'contact': contact,
    })     

adminpanel/templates/adminlte/admin_panel.html
{% extends "adminlte/index_panel.html" %}



{% block content %}
      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Small boxes (Stat box) -->
          <div class="row">
            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-info">
                <div class="inner">
                  <h3>{{ orders_count }}</h3>
  
                  <p>سفارشات</p>
                </div>
                <div class="icon">
                  <i class="ion ion-bag"></i>
                </div>
                <a href="{% url 'admin_panel:orders_list_admin' %}" target="_blank" class="small-box-footer">دیدن همه ی سفارشات <i class="fas fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-success">
                <div class="inner">
                  <h3>{{ product_count }}</h3>
  
                  <p>تعداد اجناس</p>
                </div>
                <div class="icon">
                  <i class="ion ion-stats-bars"></i>
                </div>
                <a href="{% url 'admin_panel:products_list_admin' %}" class="small-box-footer">دیدن همه ی اجناس <i class="fas fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-warning">
                <div class="inner">
                  <h3>{{ users_count }}</h3>
  
                  <p>کاربران</p>
                </div>
                <div class="icon">
                  <i class="ion ion-person-add"></i>
                </div>
                <a href="" target="_blank" class="small-box-footer">دیدن همه ی کاربران <i class="fas fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-danger">
                <div class="inner">
                  <h3>
                      {{ ticket_count }}
                  </h3>
  
                  <p>تعداد تیکت ها</p>
                </div>
                <div class="icon">
                  <i class="ion ion-pie-graph"></i>
                </div>
                <a href="{% url 'admin_panel:tickets_list_admin' %}" target="_blank" class="small-box-footer"> دیدن همه تیکت ها<i class="fas fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
          </div>
  
        </div>
      </section>
      <!-- /.content -->
  
  {# -------------------ORDERS------------------ #}
      <div class="col-12">
        <div class="card">
          <div class="card-header border-transparent">
            <h3 class="card-title">سفارشات</h3>
  
            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fas fa-minus"></i>
              </button>
              <button type="button" class="btn btn-tool" data-card-widget="remove">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body p-0">
            <div class="table-responsive">
              <table class="table m-0" style="font-size: 13px;">
                <thead>
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>نام</th>
                      <th>نام خانوادگی</th>
                      <th>تاریخ</th>
                      <th>مبلغ</th>
                      <th>وضعیت</th>
                      <th>کد پستی</th>
                      <th>شهر</th>
                      <th>آدرس</th>
                    </tr>
                  </thead>
                </thead>
                <tbody>
                  {% if orders %}
                    {% for order in orders %}
                        <tr>
                          <td>{{ forloop.counter }}</td>
                          <td>{{ order.first_name }}</td>
                          <td>{{ order.last_name }}</td>
                          <td>{{ order.jcreated_at }}</td>
                          <td>{{ order.get_total_cost }} تومان</td>
                          <td><span class="badge {% if order.status == 1 %}
                                    badge-info
                                    {% elif order.status == 2 %}
                                        badge-success
                                    {% elif order.status == 3 %}
                                        badge-danger
                                    {% endif %}">{{ order.get_status_display }}</span></td>
                          <td><span class="tag tag-warning">{{ order.postal_code }}</span></td>
                          <td>{{ order.city}}</td>
                          <td>{{ order.address}}</td>
                        </tr>
                    {% endfor %}
                  {% else %}
                      <td colspan="8"><p>سفارشی ندارین :)</p></td>
                  {% endif %}
                </tbody>
              </table>
            </div>
            <!-- /.table-responsive -->
          </div>
          <!-- /.card-body -->
          <div class="card-footer clearfix">
            <a href="{% url 'admin_panel:orders_list_admin' %}" class="btn btn-sm btn-info float-left">همه سفارشات</a>
          </div>
          <!-- /.card-footer -->
        </div>
        
      </div>
  
  <!-- TABLE: LATEST ORDERS -->
  <div class="col-12">
    <div class="card">
      <div class="card-header border-transparent">
        <h3 class="card-title">آخرین پیام ها</h3>
  
        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse">
            <i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" data-card-widget="remove">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body p-0">
        <div class="table-responsive">
          <table class="table m-0">
            <thead>
            <tr>
              <th>#</th>
              <th>نام و نام خانوادگی</th>
              <th>ایمیل</th>
              <th>تاریخ ارسال</th>
            </tr>
            </thead>
            <tbody>
              {% for item in contact %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td><a href="{% url 'admin_panel:contact_details_admin' id=item.id %}">{{ item.name }}</a></td>
                  <td>
                    <div class="sparkbar" data-color="#f56954" data-height="20">{{ item.email }}</div>
                  </td>
                  <td>
                    <div class="sparkbar" data-color="#f56954" data-height="20">{{ item.jcreated_at }}</div>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.card-body -->
      <div class="card-footer clearfix">
        <a href="{% url 'admin_panel:contact_list_admin' %}" class="btn btn-sm btn-info float-left">همه پیام ها</a>
      </div>
      <!-- /.card-footer -->
    </div>
    </div>

  <!-- TABLE: LATEST ORDERS -->
    <div class="col-12">
  <div class="card">
    <div class="card-header border-transparent">
      <h3 class="card-title">آخرین تیکت ها</h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse">
          <i class="fas fa-minus"></i>
        </button>
        <button type="button" class="btn btn-tool" data-card-widget="remove">
          <i class="fas fa-times"></i>
        </button>
      </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
      <div class="table-responsive">
        <table class="table m-0">
          <thead>
          <tr>
            <th>#</th>
            <th>نام و نام خانوادگی</th>
            <th>موضوع</th>
            <th>وضعیت</th>
            <th>تاریخ ایجاد</th>
            <th>تاریخ بروز رسانی</th>
          </tr>
          </thead>
          <tbody>
            {% for item in open_tickets %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'admin_panel:ticket_details_admin' id=item.id %}">{{ item.user.get_full_name }}</a></td>
                <td>{{ item.get_subject_display }}</td>
                <td>
                  <span class="badge 
                  {% if item.status == 1 %}
                  badge-info
                  {% elif item.status == 2 %}
                  badge-warning
                  {% elif item.status == 3 %}
                  badge-success
                  {% elif item.status == 4 %}
                  badge-danger
                  {% endif %}">{{ item.get_status_display }}</span>
                </td>
                <td>
                  <div class="sparkbar" data-color="#f56954" data-height="20">{{ item.jcreated_at }}</div>
                </td>
                <td>
                  <div class="sparkbar" data-color="#f56954" data-height="20">{{ item.jupdated_at }}</div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix">
      <a href="{% url 'admin_panel:tickets_list_admin' %}" class="btn btn-sm btn-info float-left">همه تیکت ها</a>
    </div>
    <!-- /.card-footer -->
  </div>
  </div>
  
    <div class="col-12">
      <div class="card">
        <div class="card-header border-transparent">
          <h3 class="card-title">فروش هر محصول</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
          <div class="table-responsive">
            <table class="table m-0">
              <thead>
                <thead>
                  <tr>
                    <th>#</th>
                    <th>نام محصول</th>
                    <th>تعداد فروش</th>
                    <th>کل فروش</th>
                  </tr>
                </thead>
              </thead>
              <tbody>
                {% for order in sale %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ order.product__name }}</td>
                        <td>{{ order.quantity__sum }} عدد</td>
                        <td>{{ order.total_price__sum }} تومان</td>
                      </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <!-- /.table-responsive -->
        </div>
        <!-- /.card-body -->
        <div class="card-footer clearfix">
          <a href="javascript:void(0)" class="btn btn-sm btn-info float-left">همه محصولات</a>
        </div>
        <!-- /.card-footer -->
      </div>
        <!-- /.card -->
        
        <!-- /.card -->
      </div>
      <!-- /.col -->
      </div>
    </div>
{% endblock content %}

adminpanel/templates/adminlte/contact_list_admin.html
{% extends "adminlte/index_panel.html" %}


{% block title %}
پنل مدیریت | لیست پیام های مخاطبان
{% endblock title %}



{% block content %}
<!-- /.row -->
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                <h3 class="card-title">جدول کل پیام های مخاطبان</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                        <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                    </div>
                    </div>
                </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                <table class="table table-hover" style="font-size: 13px;">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th> نام و نام خانوادگی</th>
                        <th>ایمیل</th>
                        <th>تاریخ ارسال</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% if contact %}
                          {% for item in contact %}
                              <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{% url 'admin_panel:contact_details_admin' id=item.id %}">{{ item.name }}</a></td>
                                <td>{{ item.email }}</td>
                                <td>{{ item.jcreated_at }}</td>
                              </tr>
                          {% endfor %}
                        {% else %}
                            <td colspan="8"><p>پیامی ندارین :)</p></td>
                        {% endif %}
                    </tbody>
                </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>
{% endblock content %}

adminpanel/templates/adminlte/order_list_admin.html
{% extends "adminlte/index_panel.html" %}


{% block title %}
پنل مدیریت | لیست سفارشات
{% endblock title %}



{% block content %}
<!-- /.row -->
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                <h3 class="card-title">جدول کل سفارشات</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                        <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                    </div>
                    </div>
                </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                <table class="table table-hover" style="font-size: 13px;">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>نام</th>
                        <th>نام خانوادگی</th>
                        <th>تاریخ</th>
                        <th>مبلغ</th>
                        <th>وضعیت</th>
                        <th>کد پستی</th>
                        <th>شهر</th>
                        <th>آدرس</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% if orders %}
                          {% for order in orders %}
                              <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ order.first_name }}</td>
                                <td>{{ order.last_name }}</td>
                                <td>{{ order.jcreated_at }}</td>
                                <td>{{ order.get_total_cost }} تومان</td>
                                <td><span class="badge {% if order.status == 1 %}
                                          badge-info
                                          {% elif order.status == 2 %}
                                              badge-success
                                          {% elif order.status == 3 %}
                                              badge-danger
                                          {% endif %}">{{ order.get_status_display }}</span></td>
                                <td><span class="tag tag-warning">{{ order.postal_code }}</span></td>
                                <td>{{ order.city}}</td>
                                <td>{{ order.address}}</td>
                              </tr>
                          {% endfor %}
                        {% else %}
                            <td colspan="8"><p>سفارشی ندارین :)</p></td>
                        {% endif %}
                    </tbody>
                </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>
{% endblock content %}

adminpanel/templates/adminlte/sidebar.html
{% load static %}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{% static 'adminlte/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text">محصولات کشاورزی</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'adminlte/dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ user.get_full_name }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                مدیریت
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'admin_panel:management' %}" class="nav-link active">
                  <i class="fa fa-list nav-icon"></i>
                  <p>پنل مدیریت</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'admin_panel:orders_list_admin' %}" target="_blank" class="nav-link">
                  <i class="fa fa-shopping-basket nav-icon"></i>
                  <p>سفارشات</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'admin_panel:contact_list_admin' %}" target="_blank" class="nav-link">
                  <i class="fa fa-user-friends nav-icon"></i>
                  <p>پیام ها</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'admin_panel:tickets_list_admin' %}" target="_blank" class="nav-link">
                  <i class="fa fa-user-friends nav-icon"></i>
                  <p>تیکت ها</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="{% url 'profile' %}" class="nav-link">
              <i class="nav-icon fa fa-user-circle"></i>
              <p>
                پروفایل
                <span class="right badge badge-danger">جدید</span>
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">پنل مدیریت سایت</h1>
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

adminpanel/templates/adminlte/tickets_list_admin.html
{% extends "adminlte/index_panel.html" %}

{% block title %}
پنل مدیریت | لیست تیکت ها
{% endblock title %}


{% block content %}
<!-- /.row -->
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                <h3 class="card-title">جدول تیکت ها</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                        <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                    </div>
                    </div>
                </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                <table class="table table-hover" style="font-size: 13px;">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>نام و نام خانوادگی</th>
                        <th>موضوع</th>
                        <th>وضعیت</th>
                        <th>تاریخ ایجاد</th>
                        <th>تاریخ بروز رسانی</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% if tickets %}
                        {% for item in tickets %}
                        <tr>
                          <td>{{ forloop.counter }}</td>
                          <td><a href="{% url 'admin_panel:ticket_details_admin' id=item.id %}">{{ item.user.get_full_name }}</a></td>
                          <td>{{ item.get_subject_display }}</td>
                          <td>
                            <span class="badge 
                            {% if item.status == 1 %}
                            badge-info
                            {% elif item.status == 2 %}
                            badge-warning
                            {% elif item.status == 3 %}
                            badge-success
                            {% elif item.status == 4 %}
                            badge-danger
                            {% endif %}">{{ item.get_status_display }}</span>
                          </td>
                          <td>
                            <div class="sparkbar" data-color="#f56954" data-height="20">{{ item.jcreated_at }}</div>
                          </td>
                          <td>
                            <div class="sparkbar" data-color="#f56954" data-height="20">{{ item.jupdated_at }}</div>
                          </td>
                        </tr>
                      {% endfor %}
                        {% else %}
                            <td colspan="8"><p>سفارشی ندارین :)</p></td>
                        {% endif %}
                    </tbody>
                </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

{% endblock content %}