blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('blog_details/<str:slug>', views.blog_details, name='blog_details'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('contact/', views.contact, name = 'contact'),
    path('product_list', views.product_list, name = 'product_list'),
    path('product_list/<str:category_slug>/', views.product_list, name = 'product_list_category'),
    path('product_list_brand/<str:brand_slug>/', views.product_list, name = 'product_list_brand'),
    path('product_detail/<int:id>/<str:slug>/', views.product_detail, name='product_detail'),
    path('addـcomment/<int:id>/', views.add_comment, name='add_comment'),
]

tickets/urls.py
from django.urls import path
from . import views

app_name = 'ticket'

urlpatterns = [
    path('', views.ticket_list, name='ticket_list'),
    path('ticket_details/<int:id>/', views.ticket_details, name='ticket_details'),
    path('add_ticket/', views.add_ticket, name='add_ticket'),
    path('add_ticketcomment/<int:id>/', views.add_ticketcomment, name='add_ticketcomment'),
]

tickets/models.py
from django.db import models
from accounts.models import User
from extensions.utils import jalali_converter
from django.urls import reverse

# Create your models here.
class Ticket(models.Model):
    class Meta:
        verbose_name = 'تیکت'
        verbose_name_plural = 'تیکت ها'
        ordering = ['-updated_at']

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')

    GARDENING = 1
    AGRICULTURE = 2
    SALES = 3
    SUBJECT_CHOICES = (
        (GARDENING, 'باغبانی'),
        (AGRICULTURE, 'کشاورزی'),
        (SALES, 'فروش'),
    )
    subject = models.IntegerField('موضوع', choices=SUBJECT_CHOICES)
    text = models.TextField('متن')
    image = models.ImageField('عکس', upload_to='product/ticket', null=True, blank=True)

    OPEN = 1
    PENDING = 2
    ANSWERD = 3
    CLOSED  = 4

    STATUS_CHOICES = (
        (OPEN, 'باز'),
        (PENDING, 'در حال بررسی'),
        (ANSWERD, 'پاسخ داده شده'),
        (CLOSED, 'بسته شده'),
    )
    status = models.IntegerField('وضعیت', choices=STATUS_CHOICES, default=1)

    
    created_at = models.DateTimeField('تاریخ ایجاد', auto_now_add=True)
    updated_at = models.DateTimeField('تاریخ بروز رسانی', auto_now=True)
    
    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('ticket:ticket_details', args=[str(self.id)])    

    
    def jcreated_at(self):
        return jalali_converter(self.created_at)
    jcreated_at.short_description = 'تاریخ ثبت'  

    def jupdated_at(self):
        return jalali_converter(self.updated_at)
    jupdated_at.short_description = 'تاریخ به روز کردن '     

class TicketComment(models.Model):
    class Meta:
        verbose_name = 'جواب تیکت'
        verbose_name_plural = 'جواب های تیکت'
        ordering = ['-updated_at']  

    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='comments', verbose_name='تیکت')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نویسنده')
    text = models.TextField('متن')
    image = models.ImageField('عکس', upload_to='product/ticketcomment', null=True, blank=True)      

    created_at = models.DateTimeField('تاریخ ایجاد', auto_now_add=True)
    updated_at = models.DateTimeField('تاریخ بروز رسانی', auto_now=True)

    def __str__(self):
        return self.ticket.user.username

    
    def jcreated_at(self):
        return jalali_converter(self.created_at)
    jcreated_at.short_description = 'تاریخ سفارش'  

    def jupdated_at(self):
        return jalali_converter(self.updated_at)
    jupdated_at.short_description = 'تاریخ به روز کردن سفارش'     

tickets/forms.py
from django import forms
from .models import Ticket, TicketComment

class TicketCreateForm(forms.ModelForm):
    subject = forms.ChoiceField(choices=Ticket.SUBJECT_CHOICES)
    class Meta:
        model = Ticket
        fields = ('text', 'image')

class TicketCommentCreateForm(forms.ModelForm):
    class Meta:
        model = TicketComment
        fields = ('text', 'image')


class TicketCommentCreateAdminForm(forms.ModelForm):
    status = forms.ChoiceField(choices=Ticket.STATUS_CHOICES)
    class Meta:
        model = TicketComment
        fields = ('text', 'image')

tickets/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Ticket, TicketComment
from .forms import TicketCreateForm, TicketCommentCreateForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import send_mail

# Create your views here.
@login_required
def ticket_list(request):
    tickets = Ticket.objects.filter(user=request.user)
    return render(request, 'tickets/ticket_list.html', {
        'tickets': tickets,
    })

@login_required
def ticket_details(request, id):
    ticket = get_object_or_404(Ticket, user_id=request.user.id, id=id)
    return render(request, 'tickets/ticket_details.html', {
        'ticket': ticket,
        'ticketcomment': TicketComment.objects.filter(ticket_id=id),
    })

@login_required
def add_ticket(request):
    if request.method == 'POST':
        form = TicketCreateForm(request.POST)
        if form.is_valid():
            ticket = Ticket()
            ticket.subject = form.cleaned_data['subject']
            ticket.text = form.cleaned_data['text']
            ticket.image = form.cleaned_data['image']
            ticket.user = request.user
            ticket.save()
            # تنظیمات ارسال فاکتور خرید با ایمیل
            subject = 'سوال شما ثبت شد'
            message = f'با سلام و خسته نباشید {request.user.username}'
            
            send_mail(subject,
            message,
            'coolgertn@gmail.com', 
            [ticket.user.email], 
            fail_silently=False)

            messages.success(request, 'تیکت شما با موفقیت ایجاد شد.')
            return HttpResponseRedirect(reverse('ticket:ticket_details', args=[ticket.id]))
    else:
        form = TicketCreateForm()
    return render(request, 'tickets/add_ticket.html', {
            'form': form,
        })

def add_ticketcomment(request, id):
    url = request.META.get('HTTP_REFERER')  
    if request.method == 'POST':
        form = TicketCommentCreateForm(request.POST)
        if form.is_valid():
            comment = TicketComment()
            comment.text = form.cleaned_data['text']
            comment.image = form.cleaned_data['image']
            comment.ticket_id = id
            comment.author_id = request.user.id 
            comment.save()
            # تنظیمات ارسال فاکتور خرید با ایمیل
            subject = 'سوال شما ثبت شد'
            message = f'با سلام و خسته نباشید {comment.ticket.user.username}'
            
            send_mail(subject,
            message,
            'coolgertn@gmail.com', 
            [comment.ticket.user.email], 
            fail_silently=False)

            messages.success(request, 'تیکت شما با موفقیت ثبت شد. ممنون از ارسال تیکت شما...')
            return HttpResponseRedirect(url)
    else:
        form = TicketCommentCreateForm()
    return HttpResponseRedirect(url)        

tickets/templates/tickets/add_ticket.html
{% extends "products/index.html" %}
{% load static %}


{% block title %}
    ایجاد تیکت         
{% endblock title %}


{% block content %}
    
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'products/img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>ایجاد تیکت</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'product:home' %}">خانه</a>
                            <span>ایجاد تیکت</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Contact Form Begin -->
    <div class="contact-form spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="contact__form__title">
                        <h2>ارسال تیکت</h2>
                    </div>
                </div>
            </div>
            <form method="post" action="{% url 'ticket:add_ticket' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <label for="username">نام و نام خانوادگی:</label>
                        <input type="text" id="username" value="{% if request.user.first_name %}{{ request.user.first_name }} {{ request.user.last_name }}{% else %}{{ request.user.username }}
                        {% endif %}" disabled>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <label for="email">ایمیل:</label>
                        <input type="text" id="email" value="{{ request.user.email }}" disabled>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <label for="subject">موضوع:</label>
                        <select name="subject" id="subject" class="form-select mb-2" aria-label="Default select example">
                            <option selected>. . . .</option>
                            <option value="1">کشاورزی</option>
                            <option value="2">باغبانی</option>
                            <option value="3">فروش</option>
                        </select>
                    </div>
                    <div class="col-lg-12 text-center">
                        <textarea name="text" placeholder="سوال شما"></textarea>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <label for="image">عکس:</label>
                        <input style="border: none;" type="file" name="image" class="form-control-file" id="image">
                    </div>
                    <div class="col-lg-12 text-center">
                        <button type="submit" class="site-btn">ارسال</button>
                    </div>
                </div>
                
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                                (<strong>{{ field.label|escape }}</strong>)
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %} 
            </form>
        </div>
    </div>
    <!-- Contact Form End -->
{% endblock content %}  

tickets/templates/tickets/ticket_details.html
{% extends "products/index.html" %}
{% load static %}

{% block title %}
  تیکت من
{% endblock title %}

{% block content %}
      <!-- Breadcrumb Section Begin -->
      <section class="breadcrumb-section set-bg" data-setbg="{% static 'products/img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2> تیکت من</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'product:home' %}">خانه</a>
                            <a href="{% url 'ticket:ticket_list' %}">لیست تیکت ها</a>
                            <span> تیکت من</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
              <div class="col-lg-12 mb-2">
                <form class="row g-3" method="post" action="{% url 'ticket:add_ticketcomment' id=ticket.id %}">
                  {% csrf_token %}
                  <div class="mb-3 col-lg-6 col-md-6">
                    <label for="exampleFormControlInput1" class="form-label">نام و نام خانوادگی</label>
                    <input type="email" name="username" class="form-control" id="exampleFormControlInput1" value="{% if request.user.first_name %}{{ request.user.first_name }} {{ request.user.last_name }}{% else %}{{ request.user.username }}
                    {% endif %}" disabled>
                  </div>
                  <div class="mb-3 col-lg-6 col-md-6">
                    <label for="exampleFormControlInput1" class="form-label">ایمیل</label>
                    <input type="email" name="email" class="form-control" id="exampleFormControlInput1" value="{{ request.user.email }}" disabled>
                  </div>
                  <div class="mb-3 col-lg-12">
                    <label for="exampleFormControlTextarea1" class="form-label">متن</label>
                    <textarea class="form-control" name="text" id="exampleFormControlTextarea1" rows="3"></textarea>
                  </div>
                  
                  <div class="mb-3 col-lg-6 col-md-6">
                    <label for="image">عکس:</label>
                    <input style="border: none;" type="file" name="image" class="form-control-file" id="image">
                  </div>

                  <div class="col-12">
                    <button type="submit" class="site-btn">ارسال</button>
                  </div>
                  {% if form.errors %}
                      {% for field in form %}
                          {% for error in field.errors %}
                              <div class="alert alert-danger">
                                  <strong>{{ error|escape }}</strong>
                                  (<strong>{{ field.label|escape }}</strong>)
                              </div>
                          {% endfor %}
                      {% endfor %}
                      {% for error in form.non_field_errors %}
                          <div class="alert alert-danger">
                              <strong>{{ error|escape }}</strong>
                          </div>
                      {% endfor %}
                  {% endif %}
                </form>
              </div>
              <div class="col-lg-12">
                {% for comment in ticketcomment %}
                  <div class="card mb-2">
                    <div class="card-header header_card_ticket {% if comment.author.is_staff %}
                    bg-info
                    {% endif %}">
                      <p class="name"><i class="fa fa-user"></i> {{ comment.author.first_name }} {{ comment.author.last_name }}</p>
                      <p class="created_at">{{ comment.jcreated_at }}</p>
                    </div>
                    <div class="card-body">
                      <blockquote class="blockquote mb-0">
                        <p class="text_ticket">{{ comment.text|striptags|urlize|linebreaks }}</p>
                      </blockquote>
                    </div>
                  </div>
                {% endfor %}
              </div>
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header header_card_ticket">
                          <p class="name"><i class="fa fa-user"></i> {{ ticket.user.first_name }} {{ ticket.user.last_name }}</p>
                          <p class="created_at">{{ ticket.jcreated_at }}</p>
                        </div>
                        <div class="card-body">
                            <p class="text_ticket">{{ ticket.text|linebreaks }}</p>
                        </div>
                      </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shoping Cart Section End -->
{% endblock content %}

tickets/templates/tickets/ticket_list.html
{% extends "products/index.html" %}
{% load static %}

{% block title %}
  لیست تیکت ها
{% endblock title %}

{% block content %}
      <!-- Breadcrumb Section Begin -->
      <section class="breadcrumb-section set-bg" data-setbg="{% static 'products/img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>لیست تیکت ها</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'product:home' %}">خانه</a>
                            <span>لیست تیکت ها</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th class="shoping__product">نام</th>
                                    <th>نام خانوادگی</th>
                                    <th>موضوع</th>
                                    <th>وضعیت</th>
                                    <th>تاریخ</th>
                                    <th> تاریخ  بروز شده</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in tickets %}
                                    <tr style="font-size: 15px;">
                                        <td>
                                            {{ item.user.first_name }}
                                        </td>
                                        <td>
                                            {{ item.user.last_name }}
                                        </td>
                                        <td>
                                            {{ item.get_subject_display }}
                                        </td>
                                        <td>
                                            <span class="badge {% if item.status == 1 %}
                                                badge-info
                                            {% elif item.status == 2 %}
                                                badge-warning
                                            {% elif item.status == 3 %}
                                                badge-success
                                            {% elif item.status == 4 %}
                                                badge-danger
                                            {% endif %}">{{ item.get_status_display }}</span>
                                        </td>
                                        <td>
                                            {{ item.jcreated_at }}
                                        </td>
                                        <td>
                                            {{ item.jupdated_at }}
                                        </td>
                                        <td>
                                            <a style="color: #fff;" href="{{ item.get_absolute_url }}" class="badge bg-primary">جزئیات</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shoping Cart Section End -->
{% endblock content %}