blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('blog_details/<str:slug>', views.blog_details, name='blog_details'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_details'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [ 
    path('coupon_apply/', views.coupon_apply, name='coupon_apply'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('contact/', views.contact, name = 'contact'),
    path('product_list', views.product_list, name = 'product_list'),
    path('product_list/<str:category_slug>/', views.product_list, name = 'product_list_category'),
    path('product_list_brand/<str:brand_slug>/', views.product_list, name = 'product_list_brand'),
    path('product_detail/<int:id>/<str:slug>/', views.product_detail, name='product_detail'),
    path('addـcomment/<int:id>/', views.add_comment, name='add_comment'),
]

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from coupons.models import Coupon


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_details')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_details')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    coupon_apply_form = CouponApplyForm()

    return render(request, 'cart/cart_details.html',
                           {'cart': cart,
                            'coupon_apply_form': coupon_apply_form,})

cart/templates/cart/cart_details.html
{% extends "products/index.html" %}
{% load static %}

{% block title %}
  سبد خرید
{% endblock title %}

{% block content %}
      <!-- Breadcrumb Section Begin -->
      <section class="breadcrumb-section set-bg" data-setbg="{% static 'products/img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>سبد خرید</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'product:home' %}">خانه</a>
                            <span>سبد خرید</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th class="shoping__product">محصولات</th>
                                    <th>قیمت</th>
                                    <th>تعداد</th>
                                    <th></th>
                                    <th></th>
                                    <th>قیمت کل</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                {% with product=item.product %}
                                    <tr>
                                        <td class="shoping__cart__item">
                                            <img style="width: 100px; height: 100px;" src="{{ product.image.url }}" alt="">
                                            <h5><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
                                        </td>
                                        <td class="shoping__cart__price">
                                            {{ product.price }}تومان
                                        </td>
                                        <td colspan="3" class="shoping__cart__quantity">
                                            <div class="quantity">
                                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                                    {% csrf_token %}
                                                    <div class="pro-qty">
                                                        <input type="text" name="quantity" value="{{ item.quantity }}">
                                                        <input type="hidden" name="override" value="{{ item.quantity }}">
                                                    </div>
                                                    <button type="submit" class="primary-btn cart-btn cart-btn-right"><span class="icon_loading"></span>
                                                        به روز کردن سبد</button>
                                                </form>
                                            </div>
                                        </td>
                                        <td class="shoping__cart__total">
                                            {{ item.total_price  }} تومان
                                        </td>
                                        <td class="shoping__cart__item__close">
                                            <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                              <button type="submit" style="border: none; background-color: #fff;"><span class="icon_close"></span></button>
                                              {% csrf_token %}
                                            </form>
                                        </td>
                                    </tr>
                                  {% endwith %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__btns">
                        <a href="{% url 'product:product_list' %}" class="primary-btn cart-btn">ادامه خرید</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__continue">
                        <div class="shoping__discount">
                            <h5>کد تخفیف</h5>
                            <form action="{% url 'coupons:coupon_apply' %}" method="post">
                                {% csrf_token %}
                                <input type="text" name="code" placeholder="کد تخفیف را وارد نمایید">
                                <button type="submit" class="site-btn">ثبت کد نخفیف</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__checkout">
                            <h5>هزینه سبد</h5>
                            <ul>
                                <li>هزینه بدون تخفیف <span>{{ cart.get_total_price }} تومان</span></li>
                                {% if cart.coupon %}
                                    {% with code=cart.coupon.code discount=cart.coupon.discount %}
                                    <li> کد "{{ code }}"({{ discount }}% تخفیف)</li>
                                    {% endwith %}
                                {% endif %}
                                <li>کل <span>{{ cart.get_total_price_after_discount|floatformat:0 }} تومان</span></li>
                            </ul>
                            <a href="{% url 'order:order_create' %}" class="primary-btn">سفارش</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shoping Cart Section End -->
{% endblock content %}