blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('blog_details/<str:slug>', views.blog_details, name='blog_details'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('contact/', views.contact, name = 'contact'),
    path('product_list', views.product_list, name = 'product_list'),
    path('product_list/<str:category_slug>/', views.product_list, name = 'product_list_category'),
    path('product_list_brand/<str:brand_slug>/', views.product_list, name = 'product_list_brand'),
    path('product_detail/<int:id>/<str:slug>/', views.product_detail, name='product_detail'),
    path('addـcomment/<int:id>/', views.add_comment, name='add_comment'),
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Blog(models.Model):
    class Meta:
        verbose_name = 'بلاگ'
        verbose_name_plural = 'بلاگ ها'

    title = models.CharField('عنوان بلاگ', max_length=128)
    slug = models.SlugField('اسلاگ بلاگ', allow_unicode=True, max_length=128)
    poster = models.ImageField('پوستر بلاگ', upload_to='product/blogs')
    text = RichTextField('متن بلاگ')


    created_at = models.DateTimeField('تاریخ ایجاد', auto_now_add=True)
    updated_at = models.DateTimeField('تاریخ بروز رسانی', auto_now=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def blog(request):
    blogs = Blog.objects.all().order_by('-created_at')
    return render(request, 'blog/blog.html', {
        'blogs': blogs,
    })

def blog_details(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    return render(request, 'blog/blog_details.html', {
        'blog': blog,
    })    

blog/templates/blog/blog.html
{% extends "products/index.html" %}
{% load static %}
{% load base_tags %}

{% block title %}
  بلاگ
{% endblock title %}

{% block content %}

        <!-- Breadcrumb Section Begin -->
        <section class="breadcrumb-section set-bg" data-setbg="{% static 'products/img/breadcrumb.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="breadcrumb__text">
                            <h2>بلاگ ها</h2>
                            <div class="breadcrumb__option">
                                <a href="{% url 'product:home' %}">خانه</a>
                                <span>بلاگ</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Breadcrumb Section End -->
    
        <!-- Product Section Begin -->
        <section class="product spad">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="product__item row">
                            {% for blog in blogs %}
                                <div class="col-lg-4 col-md-4 col-sm-6">
                                    <div class="blog__item">
                                        <div class="blog__item__pic">
                                            <img src="{{ blog.poster.url }}" alt="">
                                        </div>
                                        <div class="blog__item__text">
                                            <ul>
                                                <li><i class="fa fa-calendar-o"></i> {{ blog.created_at }}</li>
                                                <li><i class="fa fa-comment-o"></i> 0</li>
                                            </ul>
                                            <h5><a href="{% url 'blog:blog_details' slug=blog.slug %}">{{ blog.title }}</a></h5>
                                            <p>{{ blog.text|safe|truncatechars:50 }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

                        <div class="col-12 product__pagination">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-long-arrow-right"></i></a>
                                {% if page_obj.number > 3 %}
                                    <a href="?page=1">1</a>
                                {% endif %}
                            {% endif %}

                            {% for num in page_obj.paginator.page_range %}
                                {% if page_obj.number == num %}
                                    <span class="current">
                                        <a href="" style="background-color: #7fad39; color: #fff;">{{ page_obj.number }}</a>
                                    </span>
                                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                    <a href="?page={{num}}">{{num}}</a>
                                {% endif %}
                            {% endfor %}


                            {% if page_obj.has_next %}
                                {% if page_obj.number < 3 %}
                                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                                {% endif %}
                                <a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-long-arrow-left"></i></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Product Section End -->
{% endblock content %}

blog/templates/blog/blog_details.html
{% extends "products/index.html" %}
{% load static %}
{% load base_tags %}

{% block title %}
  بلاگ
{% endblock title %}

{% block content %}

        <!-- Breadcrumb Section Begin -->
        <section class="breadcrumb-section set-bg" data-setbg="{% static 'products/img/breadcrumb.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="breadcrumb__text">
                            <h2>بلاگ ها</h2>
                            <div class="breadcrumb__option">
                                <a href="{% url 'product:home' %}">خانه</a>
                                <a href="{% url 'blog:blog' %}">بلاگ</a>
                                <span>{{ blog.title }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Breadcrumb Section End -->
    
        <!-- Product Section Begin -->
        <section class="product spad">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="blog__item">
                            <h1>{{ blog.title }}</h1>
                            <div class="blog__item__pic">
                                <img src="{{ blog.poster.url }}" alt="">
                            </div>
                            <div class="blog__item__text">
                                <ul>
                                    <li><i class="fa fa-calendar-o"></i> {{ blog.created_at }}</li>
                                    <li><i class="fa fa-comment-o"></i> 0</li>
                                </ul>
                                <h5><a href="#">{{ blog.title }}</a></h5>
                                <p>{{ blog.text|safe }}</p>
                            </div>
                        </div>
                    </div>
                </div>
        </section>
        <!-- Product Section End -->
{% endblock content %}